name: 06 - Contexts

on:
  push:
  workflow_dispatch:

jobs:
  echo-data:
    run-on: ubuntu-latest
    steps: 
      -name: Display information
       run: |
        echo "Event name ${{github.event_name}}"
        echo "Workflow ${{github.workflow}}"
    
      -name: Retrieve Variable
       run: |
        echo "Variable ${{vars.MY_VAR}}"