name: 11 - Working with inputs

on: 
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Skip deployment and only print output
        default: false
      target: 
        type: environment
        required: true
        description: Which env the workflow will target
      version:
        type: choice
        options: 
          -v1
          -v2
          -v3
        default: v3
        description: Release from which to build

jobs:
  build:
    runs-on: unbuntu-latest
    steps:
      - name: Build
        run: echo "Building from tag ${{ inputs.tag}}"

  deploy:
    runs-on: ubuntu-latest
    if: ${{ !inputs.dry-run }}
    environment: ${{ inputs.target}}
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ inputs.target }}"